[package]
name = "cncli"
version = "0.2.8"
authors = ["Andrew Westberg <andrewwestberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2b_simd = "0.5.11"
byteorder = "1.3.4"
chrono = "0.4.19"
chrono-tz = "0.5.3"
hex = "0.3.1"
libc = "0.2.80"
net2 = "0.2.35"
regex = "1.4.2"
reqwest = { version = "0.10.8", features = ["blocking"] }
rug = { version = "1.11.0", default-features = false, features = ["integer", "rational", "float", "serde"] }
rusqlite = "0.24.1"
serde = { version = "1.0.117", features = ["derive"] }
serde-aux = "1.1.0"
serde_cbor = "0.10.2"
serde_json = "1.0.59"
structopt = "0.3.20"

# logging
log = "0.4.11"
env_logger = "0.8.1"
pretty_env_logger = "0.4.0"